# This is a basic workflow to help you get started with Actions

name: M5EzBuild

# Triggers the workflow on push or pull request
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**main.yml'
  pull_request:    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Test compiling examples
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: arduino/actions/libraries/compile-examples@master
      with:
       enable-size-deltas-report: true
       fqbn: '"esp32:esp32:m5stack-core-esp32" "https://dl.espressif.com/dl/package_esp32_index.json"'
       github-token: ${{ secrets.GITHUB_TOKEN }}
       libraries: |
         - name: ezTime
         - name: M5Stack
         - source-path: ./
    - if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v1
      with:
       name: size-deltas-reports
       path: size-delta-reports
